#include "cwStrategyCommon.h"
namespace cwPandoraTrader
{
	int GetcwTradingDayRemainWarning(std::string strProductID)
	{
		if (strProductID == "IF"
			|| strProductID == "IC"
			|| strProductID == "IH"
			|| strProductID == "IM"
			|| strProductID == "cu"
			|| strProductID == "al"
			|| strProductID == "zn"
			|| strProductID == "pb"
			|| strProductID == "ni"
			|| strProductID == "sn"
			|| strProductID == "ss"
			|| strProductID == "IF_f"
			|| strProductID == "IC_f"
			|| strProductID == "IH_f"
			|| strProductID == "IM_f"
			|| strProductID == "cu_f"
			|| strProductID == "al_f"
			|| strProductID == "zn_f"
			|| strProductID == "pb_f"
			|| strProductID == "ni_f"
			|| strProductID == "sn_f"
			|| strProductID == "ss_f")
		{
			return 14;
		}
		if (strProductID == "TS"
			|| strProductID == "TF"
			|| strProductID == "T"
			|| strProductID == "pg"
			|| strProductID == "eb"
			|| strProductID == "a"
			|| strProductID == "cs"
			|| strProductID == "b"
			|| strProductID == "TS_f"
			|| strProductID == "TF_f"
			|| strProductID == "T_f"
			|| strProductID == "pg_f"
			|| strProductID == "eb_f"
			|| strProductID == "a_f"
			|| strProductID == "cs_f"
			|| strProductID == "b_f")
		{
			return 20;
		}
		if (strProductID == "au"
			|| strProductID == "ag"
			|| strProductID == "rb"
			|| strProductID == "i"
			|| strProductID == "hc"
			|| strProductID == "SF"
			|| strProductID == "SM"
			|| strProductID == "jm"
			|| strProductID == "j"
			|| strProductID == "ZC"
			|| strProductID == "FG"
			|| strProductID == "sp"
			|| strProductID == "sc"
			|| strProductID == "fu"
			|| strProductID == "lu"
			|| strProductID == "bu"
			|| strProductID == "TA"
			|| strProductID == "v"
			|| strProductID == "ru"
			|| strProductID == "nr"
			|| strProductID == "l"
			|| strProductID == "PF"
			|| strProductID == "eg"
			|| strProductID == "MA"
			|| strProductID == "pp"
			|| strProductID == "UR"
			|| strProductID == "SA"
			|| strProductID == "c"
			|| strProductID == "m"
			|| strProductID == "y"
			|| strProductID == "RM"
			|| strProductID == "OI"
			|| strProductID == "p"
			|| strProductID == "PK"
			|| strProductID == "CF"
			|| strProductID == "SR"
			|| strProductID == "jd"
			|| strProductID == "lh"
			|| strProductID == "AP"
			|| strProductID == "CJ"
			|| strProductID == "si"
			|| strProductID == "au_f"
			|| strProductID == "ag_f"
			|| strProductID == "rb_f"
			|| strProductID == "i_f"
			|| strProductID == "hc_f"
			|| strProductID == "SF_f"
			|| strProductID == "SM_f"
			|| strProductID == "jm_f"
			|| strProductID == "j_f"
			|| strProductID == "ZC_f"
			|| strProductID == "FG_f"
			|| strProductID == "sp_f"
			|| strProductID == "sc_f"
			|| strProductID == "fu_f"
			|| strProductID == "lu_f"
			|| strProductID == "bu_f"
			|| strProductID == "TA_f"
			|| strProductID == "v_f"
			|| strProductID == "ru_f"
			|| strProductID == "nr_f"
			|| strProductID == "l_f"
			|| strProductID == "PF_f"
			|| strProductID == "eg_f"
			|| strProductID == "MA_f"
			|| strProductID == "pp_f"
			|| strProductID == "UR_f"
			|| strProductID == "SA_f"
			|| strProductID == "c_f"
			|| strProductID == "m_f"
			|| strProductID == "y_f"
			|| strProductID == "RM_f"
			|| strProductID == "OI_f"
			|| strProductID == "p_f"
			|| strProductID == "PK_f"
			|| strProductID == "CF_f"
			|| strProductID == "SR_f"
			|| strProductID == "jd_f"
			|| strProductID == "lh_f"
			|| strProductID == "AP_f"
			|| strProductID == "CJ_f"
			|| strProductID == "si_f")
		{
			return 20;
		}
		return 20;
	}
}// End cwPandoraTrader NameSpace